dtb-$(CONFIG_ARCH_MSM8940) += santoni-fdt.dtb #msm8940-pmi8937-cdp.dtb \
        #msm8940-pmi8937-mtp.dtb \
        msm8940-pmi8950-cdp.dtb \
        msm8940-pmi8950-mtp.dtb \
        msm8940-pmi8937-rcm.dtb \
        msm8940-pmi8950-rcm.dtb \
        msm8940-pmi8950-qrd-sku6.dtb \
        msm8940-pmi8950-qrd-sku7.dtb \
        msm8940-pmi8950-ext-codec-cdp.dtb \
        msm8940-pmi8940-mtp.dtb \
        msm8940-pmi8940-cdp.dtb \
        msm8940-pmi8940-rcm.dtb \
        msm8940-pmi8940-qrd-sku7.dtb

